# Generated by Django 5.2 on 2025-04-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Grupo')),
                ('data_apresentacao', models.CharField(blank=True, max_length=10, verbose_name='Data (DD/MM/AAAA)')),
                ('hora_apresentacao', models.CharField(blank=True, max_length=5, verbose_name='Hora (HH:MM)')),
                ('ordem_apresentacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem')),
            ],
            options={
                'ordering': ['ordem_apresentacao'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Tema')),
                ('quantidade_grupos', models.PositiveIntegerField(verbose_name='Quantidade de Grupos')),
                ('alunos_por_grupo', models.PositiveIntegerField(verbose_name='Alunos por Grupo')),
                ('data_apresentacao', models.DateField(verbose_name='Data da Apresentação')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
            ],
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider', models.BooleanField(default=False, verbose_name='Líder')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appaula.aluno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appaula.grupo')),
            ],
        ),
    ]
