# Generated by Django 5.2 on 2025-04-25 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appaula.tema'),
        ),
    ]
